# Generated by Django 4.0.4 on 2022-05-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
