# Generated by Django 4.0.4 on 2022-05-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_worker_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='endTime',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='startTime',
            field=models.CharField(max_length=6),
        ),
    ]
