# Generated by Django 4.0.4 on 2022-06-04 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_alter_task_endtime_alter_task_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
